### ISSUE TITLE
Request for link to models in paper and correct link for training data

### ISSUE THREAD

**Issue by GenTxt** [WeazelDev/AITextGenerator#5]
Hi:

Thanks for this multi-function code factory. Having fun with this repo using custom local models. Needed to tweak 'test_generation.py' 

Currently readline() working but only reads a single line from P1 and P3 text files as strings  readlines() doesn't work because it returns a list and read() swallows everything. 

Any suggestions would be helpful.

Just  a few quick questions.

1. Do you plan on releasing the models mentioned in your paper currently with placeholders in the 'models' folder? Would appreciate links.

2. Your posted link for the training data is returning '404' Can this be corrected?
https://drive.google.com/open?id=1wfWNo4p91OPHUSBYJ9Bv-oMNawxv_tAH

3. Is there a process to convert local text files to  .json for use in the repo?

Cheers

**Comment by WeazelDev** [comment]
Hi,

I appreciate your interest in our project, however it is not over yet! We had to make this repo public to use it in AWS and Google EC2 instances.

That said, I'm glad you're trying to use it but we cannot guarantee that everything will be working for now. Especially, the model is currently in the training phase, it will be released afterward to put in the 'models' folder.

Concerning the data, the errors in code, the general usability and the documentation, all of this will come later when we clean our project files.

Most test files are quite old, using old versions of the functions and classes. I recommend you only look to the files at root and in src folder.

To produce .json files from a book or a text in general, you can look at "src/json_generation/prepare_data.py", this part should work already :)

**Comment by WeazelDev** [comment]
Hi again,
I just updated the links to the **data** and **model** archives, so you can download them.
However, currently **there is no**:

- trained generative model
- generated data from these model
- computed metrics

Currently, you will find:

- all the raw and preprocessed data files (json) --> DATA_ARCHIVE
- BERT_NER_Large weights, for entity recognition --> MODELS_ARCHIVE
